image: golang:latest

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test

before_script:
  - export PROJECT_DIR=/go/src/gitlab.com/yaotsu/gcn3
  - mkdir -p ${PROJECT_DIR}
  - cp -r ${CI_PROJECT_DIR} /go/src/gitlab.com/yaotsu
  - cd ${PROJECT_DIR} && go get -t ./...

go_build:
  stage: build
  script:
    - cd $PROJECT_DIR && go get -t ./...
    - cd $PROJECT_DIR && go build ./...
  artifacts:
    paths:
      - $GOPATH

unit_test:
  stage: test
  script:
    - go install github.com/onsi/ginkgo/ginkgo
    - cd $PROJECT_DIR && ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
    - go test -coverprofile=cover.out ./...
    - cd $PROJECT_DIR && go tool cover -func=cover.out
  dependencies:
    - go_build

acceptance_test:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq python3
    - cd $PROJECT_DIR && python3 acceptance_test.py
  dependencies:
    - go_build
