image: golang:latest

stages:
  - build
  - test
  - acceptance_test

go_build:
  stage: build
  script:
    - go build ./...

lint:
  stage: build
  script:
    - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin
    - go build ./...
    - golangci-lint run ./...

unit_test:
  stage: test
  script:
    - go install github.com/onsi/ginkgo/v2/ginkgo@v2.4.0
    - ginkgo -r --randomize-all --randomize-suites --fail-on-pending --cover --trace --progress
    - go test -coverprofile=cover.out ./...
    - go tool cover -func=cover.out > coverage.out
    - tail coverage.out

single_gpu_test:
  stage: acceptance_test
  tags:
    - multi_core
  script:
    - cd tests/acceptance
    - go build
    - ./acceptance -num-gpu=1

two_discrete_gpu_test:
  stage: acceptance_test
  tags:
    - multi_core
  script:
    - cd tests/acceptance
    - go build
    - ./acceptance -num-gpu=2 -no-unified-gpu -no-unified-memory

four_discrete_gpu_test:
  stage: acceptance_test
  tags:
    - multi_core
  script:
    - cd tests/acceptance
    - go build
    - ./acceptance -num-gpu=4 -no-unified-gpu -no-unified-memory

two_unified_gpu_test:
  stage: acceptance_test
  tags:
    - multi_core
  script:
    - cd tests/acceptance
    - go build
    - ./acceptance -num-gpu=2 -only-unified-gpu -no-unified-memory

four_unified_gpu_test:
  stage: acceptance_test
  tags:
    - multi_core
  script:
    - cd tests/acceptance
    - go build
    - ./acceptance -num-gpu=4 -only-unified-gpu -no-unified-memory

# multi_discrete_gpu_unified_memory_test:
#   stage: acceptance_test
#   tags:
#     - multi_core
#   script:
#     - cd tests/acceptance
#     - go build
#     - ./acceptance -num-gpu=2 -no-unified-gpu -only-unified-memory
#     - ./acceptance -num-gpu=4 -no-unified-gpu -only-unified-memory

# multi_unified_gpu_unified_memory_test:
#   stage: acceptance_test
#   tags:
#     - multi_core
#   script:
#     - cd tests/acceptance
#     - go build
#     - ./acceptance -num-gpu=2 -only-unified-gpu -only-unified-memory
#     - ./acceptance -num-gpu=4 -only-unified-gpu -only-unified-memory

deterministic_test:
  stage: acceptance_test
  script:
    - cd tests/deterministic/memcopy
    - go build
    - ./memcopy
    - cd ../../../
    - cd tests/deterministic/empty_kernel
    - go build
    - ./empty_kernel
