image: golang:latest

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test
  - acceptance_test
  - deploy

before_script:

go_build:
  stage: build
  script:
    - go build ./...

unit_test:
  stage: test
  script:
    - go install github.com/onsi/ginkgo/ginkgo
    - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress --skip="Stress"
    - go test -coverprofile=cover.out ./...
    - go tool cover -func=cover.out

cache_aceptance_test:
  stage: acceptance_test
  script:
    - cd timing/caches/l1v/acceptancetest/valuetest
    - go build
    - ./valuetest

acceptance_test:
  stage: acceptance_test
  tags:
    - multi_core
  script:
    - apt-get update -qq && apt-get install -y -qq python3
    - cd tests/acceptance && GOMAXPROCS=8 python3 -u acceptance_test.py

deterministic_test:
  stage: acceptance_test
  script:
    - cd timing/caches/l1v/acceptancetest/deterministictest
    - go build
    - ./deterministictest
    - cd ../../../../../
    - cd tests/deterministic/memcopy
    - go build
    - ./memcopy
    - cd ../../../
    - cd tests/deterministic/empty_kernel
    - go build
    - ./empty_kernel

build_docker_image_master:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  only:
    - master
  script:
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/dev
    - docker pull $IMAGE_NAME:latest || true
    - docker build --cache-from $IMAGE_NAME:latest --tag $IMAGE_NAME:$CI_COMMIT_SHA --tag $IMAGE_NAME:latest ./docker/dev
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:latest

build_docker_image_release:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  only:
    - tags
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest ./docker/dev
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
