image: golang:latest

before_script:
  - apt-get update -qq && apt-get install -y -qq python3

stages:
  - test

test_job:
  stage: test
  script:
  - echo $GOPATH
  - export PATH=$PATH:$GOPATH/bin
  - export PROJECT_DIR=$GOPATH/src/gitlab.com/yaotsu/gcn3
  - mkdir -p $PROJECT_DIR
  - cp -r ${CI_PROJECT_DIR}/ $GOPATH/src/gitlab.com/yaotsu/
  - echo $PROJECT_DIR
  - ls $PROJECT_DIR
  - cd $PROJECT_DIR && go get -t ./...
  - go install github.com/onsi/ginkgo/ginkgo
  - cd $PROJECT_DIR && go build ./...
  - cd $PROJECT_DIR && ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
  - cd $PROJECT_DIR && python3 acceptance_test.py
  - go test -coverprofile=cover.out ./...
  - cd $PROJECT_DIR && go tool cover -func=cover.out
